package client;

import java.awt.event.ActionListener;
import javax.swing.*;

public class ChatFrame extends JFrame {
    private String username;
    private JTextArea messageBoard;
    private JLabel messageLabel;
    private JScrollPane messagePane;
    private JTextField messageField;
    private JButton sendButton;
    private JLabel receiverLabel;
    private JTextField receiverField;
    private JLabel usernameLabel;

    public ChatFrame() {
        initComponents();
    }

    // Generated by Netbeans form designer, yuck!!
    private void initComponents() {
        usernameLabel = new JLabel();
        messagePane = new JScrollPane();
        messageBoard = new JTextArea();
        receiverLabel = new JLabel("To");
        receiverField = new JTextField();
        messageLabel = new JLabel("Message");
        messageField = new JTextField();
        sendButton = new JButton("Reply");

        messageBoard.setColumns(20);
        messageBoard.setRows(5);
        messagePane.setViewportView(messageBoard);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(messagePane, GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(receiverLabel)
                                        .addComponent(messageLabel))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(messageField)
                                        .addComponent(receiverField)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(sendButton)))
                            .addGap(10, 10, 10)))
                    .addContainerGap())
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(usernameLabel, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
                            .addGap(141, 141, 141))
                    );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(usernameLabel, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(messagePane, GroupLayout.PREFERRED_SIZE, 253, GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(receiverLabel)
                        .addComponent(receiverField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(messageLabel)
                        .addComponent(messageField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(sendButton)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        pack();
    }

    public void clearFields() {
        receiverField.setText(null);
        messageField.setText(null);
    }

    public String encode(String receiver, String message) {
        receiver = "You >> " + receiver;
        return receiver + " :: " + message;
    }

    public void addMessageToMessageBoard(String message) {
        messageBoard.append(message + "\n");
    }

    public void showErrorMessage() {
        addMessageToMessageBoard("Server >> you :: Something went wrong...");
    }

    public void setUsername(String username) {
        this.username = username;
        usernameLabel.setText(username);
    }

    public String getReceiver() {
        return receiverField.getText();
    }

    public String getMessage() {
        return messageField.getText();
    }

    public void addSendButtonListener(ActionListener sendButtonListener) {
        sendButton.addActionListener(sendButtonListener);
    }
}
